#!/bin/bash
#BSUB -J UMI                  ### set the job Name
#BSUB -q debug               ### specify queue, medium/short/debug/ser
#BSUB -n 40                  ### ask for number of cores (default: 1)
#BSUB -W 0:20             ### set walltime limit: hh:mm
#BSUB -e %J.err              ### -o and -e mean append, -oo and -eo mean overwrite
#BSUB -o %J.out              ### Specify the output and error file. %J is the job-id
#BSUB -R "span[ptile=40]"    ### ask for 40 cores per node

###### Installation of bcl2fastq------------------------------------------------------

    # export TMP=/work/bio-tanyj/buildingtmp
    # export SOURCE=${TMP}/bcl2fastq
    # export BUILD=${TMP}/bcl2fastq2-v2.19.x-build
    # export INSTALL_DIR=/work/bio-tanyj/soft/bcl2fastq
    # cd ${TMP}
    # # download file
    # tar -xvzf bcl2fastq2-v2.19.x.tar.gz

    # mkdir ${BUILD}
    # cd ${BUILD}
    # chmod ugo+x ${SOURCE}/src/configure
    # chmod ugo+x ${SOURCE}/src/cmake/bootstrap/installCmake.sh
    # ${SOURCE}/src/configure --prefix=${INSTALL_DIR}


    # # make and make install
    # cd ${TMP}
    # make
    # make install

##### Information of index and UMI (20210504)

## HCT116 -------------------------------------------------

# For data generated in `210424_E00487_0637_AHFKGFCCX2_PM-XS01KF2020070275-23`, a 6bp barcode was used as index1 (P7), and a 8bp Unique Molecular Indentifier (UMI) was used as index2 (P5).
# only use the index1 to demultiplex samples, and save the sequence of index2 in fastq.

# # date generated by Illumina plateform.
# cd /scratch/2021-05-13/bioTanyj/UMI_STARR_HCT116_Si/PM-XS01KF2020070275-28_HCT116_silencer_UMI_202105/PM-XS01KF2020070275-28_bcl/PM-XS01KF2020070275-28-2021-05-16/210511_A00511_0419_AHWK22DSXY
# /work/bio-tanyj/soft/bcl2fastq/bin/bcl2fastq \
#     --mask-short-adapter-reads 0 \
#     --sample-sheet=/scratch/2021-05-13/bioTanyj/UMI_STARR_HCT116_Si/PM-XS01KF2020070275-28_HCT116_silencer_UMI_202105/SampleSheet.csv \
#     --use-bases-mask Y150n,I6nnnn,Y8nn,Y150n \
#     # --use-bases-mask Y151,In6nnn,Y10,Y151 \
#     # --use-bases-mask Y150n,I6nnnn,Y10,Y150n \
#     # --use-bases-mask Y150n,I6nnnn,Y8nn,Y150n \
#     # --use-bases-mask Y151,In6n,Y8,Y151 \
#     --create-fastq-for-index-reads \
#     -r 38 -w 3 -p 39 \
#     -R ./ \
#     -o=./ \
#     -i=./Data/Intensities/BaseCalls/


## K562 -------------------------------------------------

# batch1 --------

# # For data generated in `210424_E00487_0637_AHFKGFCCX2_PM-XS01KF2020070275-23`, a 6bp barcode was used as index1 (P7), and a 8bp Unique Molecular Indentifier (UMI) was used as index2 (P5).
# # only use the index1 to demultiplex samples, and save the sequence of index2 in fastq.

# # date generated by Illumina plateform.
# cd /scratch/2021-06-25/bioTanyj/UMI_STARR_K562_Si/PM-XS01KF2020070275-33-2021-06-22/210616_A00511_0439_BHWLVLDSXY
# /work/bio-tanyj/soft/bcl2fastq/bin/bcl2fastq \
#     --mask-short-adapter-reads 0 \
#     --sample-sheet=/scratch/2021-06-25/bioTanyj/UMI_STARR_K562_Si/PM-XS01KF2020070275-33-2021-06-22/SampleSheet_K562_SI_UMI.csv \
#     --use-bases-mask Y150n,I6nnnn,Y8nn,Y150n \
#     # --use-bases-mask Y151,In6nnn,Y10,Y151 \
#     # --use-bases-mask Y150n,I6nnnn,Y10,Y150n \
#     # --use-bases-mask Y150n,I6nnnn,Y8nn,Y150n \
#     # --use-bases-mask Y151,In6n,Y8,Y151 \
#     --create-fastq-for-index-reads \
#     -r 38 -w 3 -p 39 \
#     -R ./ \
#     -o=./ \
#     -i=./Data/Intensities/BaseCalls/


# batch2 --------
# 210830_E00591_0456_AHGC5JCCX2
# cd /scratch/2021-09-17/bioTanyj/UMI_silencer/UMI_STARR_K562_Si/batch2_rawdata/210830_E00591_0456_AHGC5JCCX2
cd /scratch/2021-09-20/bioYanxh/210821_E00499_0700_BHG3KVCCX2_PM-XS01KF2021040035-03/210821_E00499_0700_BHG3KVCCX2
/work/bio-tanyj/soft/bcl2fastq/bin/bcl2fastq \
    --mask-short-adapter-reads 0 \
    --sample-sheet=/scratch/2021-09-20/bioYanxh/210821_E00499_0700_BHG3KVCCX2_PM-XS01KF2021040035-03/210821_E00499_0700_BHG3KVCCX2/SampleSheet_K562_SI_UMI_210830_E00591_0456_AHGC5JCCX2_562SIC25.csv \
    --use-bases-mask Y150n,I6nn,Y8,Y150n \
    # --use-bases-mask Y151,In6nnn,Y10,Y151 \
    # --use-bases-mask Y150n,I6nnnn,Y10,Y150n \
    # --use-bases-mask Y150n,I6nnnn,Y8nn,Y150n \
    # --use-bases-mask Y151,In6n,Y8,Y151 \
    --create-fastq-for-index-reads \
    -r 38 -w 3 -p 39 \
    -R ./ \
    -o=./ \
    -i=./Data/Intensities/BaseCalls/

# # 210830_E00591_0456_AHGC5JCCX2
# cd /scratch/2021-09-09/bioTanyj/UMI_silencer/UMI_STARR_K562_Si/batch2_rawdata/210830_E00572_0466_BHGC3LCCX2
# /work/bio-tanyj/soft/bcl2fastq/bin/bcl2fastq \
#     --mask-short-adapter-reads 0 \
#     --sample-sheet=/scratch/2021-09-09/bioTanyj/UMI_silencer/UMI_STARR_K562_Si/batch2_rawdata/SampleSheet_K562_SI_UMI_210830_E00572_0466_BHGC3LCCX2_562SIC27.csv \
#     --use-bases-mask Y150n,I6nn,Y8,Y150n \
#     # --use-bases-mask Y151,In6nnn,Y10,Y151 \
#     # --use-bases-mask Y150n,I6nnnn,Y10,Y150n \
#     # --use-bases-mask Y150n,I6nnnn,Y8nn,Y150n \
#     # --use-bases-mask Y151,In6n,Y8,Y151 \
#     --create-fastq-for-index-reads \
#     -r 38 -w 3 -p 39 \
#     -R ./ \
#     -o=./ \
#     -i=./Data/Intensities/BaseCalls/

#### ---------------------------------------------------- backup --------------------------------------------------------
##### Information of index and UMI (20210506, not work!) 
# For data generated in `210424_E00487_0637_AHFKGFCCX2_PM-XS01KF2020070275-23`, a 6bp barcode was used as index1 (P7), and a 8bp Unique Molecular Indentifier (UMI) was used as index2 (P5).
# only use the index1 to demultiplex samples, and save the sequence of index2 in name of reads in fastq.

# # date generated by Illumina plateform.
# cd /scratch/2021-05-03/bioTanyj/UMI_STARRseq/210424_E00487_0637_AHFKGFCCX2_PM-XS01KF2020070275-23/210424_E00487_0637_AHFKGFCCX2
# /work/bio-tanyj/soft/bcl2fastq/bin/bcl2fastq \
#     --mask-short-adapter-reads 0 \
#     --sample-sheet=/scratch/2021-05-03/bioTanyj/UMI_STARRseq/210424_E00487_0637_AHFKGFCCX2_PM-XS01KF2020070275-23/SampleSheet_20210506.csv \
#     --use-bases-mask Y150n,I6nn,Y158n \
#     --create-fastq-for-index-reads \
#     -r 38 -w 3 -p 39 \
#     -R ./ \
#     -o=/scratch/2021-05-03/bioTanyj/UMI_STARRseq/210424_E00487_0637_AHFKGFCCX2_PM-XS01KF2020070275-23/basecalling_20210506/ \
#     -i=./Data/Intensities/BaseCalls/

